# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

mio = User.create(username: "miok", password_digest: "password", firstname: "Mio", lastname: "Kataoka")
aimee = User.create(username: "aimeek", password_digest: "password", firstname: "Aimee", lastname: "Kalnoskas")
molly = User.create(username: "mollyb", password_digest: "password", firstname: "Molly", lastname: "Bergstron")
yui = User.create(username: "yuii", password_digest: "password", firstname: "Yui", lastname: "Ikeda")
fiona = User.create(username: "fionap", password_digest: "password", firstname: "Fiona", lastname: "Peck")
paul = User.create(username: "pauly", password_digest: "password", firstname: "Paul", lastname: "Yen")
louise = User.create(username: "louiser", password_digest: "password", firstname: "Louise", lastname: "Rafkin")
phyllis = User.create(username: "phyllisr", password_digest: "password", firstname: "Phyllis", lastname: "Ritchie")

dray = Dog.create(name:"Draymond", age: 4, breed: "Norwich", color: "red", user_id:mio.id)
axel = Dog.create(name:"Axel", age: 6, breed: "PWD", color: "black", user_id:phyllis.id )
mugi = Dog.create(name:"Mugi", age: 2, breed: "Pomeranian", color: "fawn", user_id:yui.id )
rose = Dog.create(name:"Rose", age: 2, breed: "Schnoodle", color: "black and white", user_id:molly.id )
stella = Dog.create(name:"Stella", age: 3, breed: "mutt", color: "fawn", user_id:aimee.id )
clover = Dog.create(name:"Clover", age: 4, breed: "Jindo", color: "cream", user_id:fiona.id )
flo = Dog.create(name:"Florence", age: 5, breed: "mutt", color: "gret", user_id:louise.id )
pawblo = Dog.create(name:"Pawblo", age: 3, breed: "Husky", color: "grey", user_id:paul.id )

item1 = Item.create(name:"martingale collar", description: "red nylong martingale collar. Size small. Dray is too low to the ground he keeps tripping over the loop.", user_id:mio.id)
item2 = Item.create(name:"fine comb", description: "I thought I misplaced the one I had and bought another one. It's perfect for combing out burrs after hiking.", user_id:phyllis.id)
item3 = Item.create(name:"pee pads", description: "I don't think Axel would need this anymore. two unopened bags of disposable pee pads. Size medium (24x40). ", user_id:phyllis.id)
item4 = Item.create(name:"small harness", description: "It still fits Dray but he just doesn't like it. Dray's neck girth is 12 inches and the chest is 20 inches. I know most of your dogs are bigger than Dray but if you know someone who can use it let me know!", user_id:mio.id)
item5 = Item.create(name:"bitter apple spray", description: "Spray on to the stuff you don't want your dog to chew on. Didn't work on Mugi though. The manufacturer also says you can use it to stop bad behaviors.", user_id:yui.id)
item6 = Item.create(name:"soft nylon puppy collar", description: "Small soft nylon puppy collar in light blue. It's really for getting your dog used to the collar and nothing more. it's really frimsy so I wouldn't attach a leash and use it like a real collar.", user_id:yui.id)
item7 = Item.create(name:"puppy food", description: "I love Natural Balance food but bought a puppy formula by mistake. I hope someone can use it. It's chicken and rice flavor.", user_id:molly.id)
item8 = Item.create(name:"nylabone", description: "Rose would rather chew on my shoes. I thought if I get her something she's allowed to chew she'd leave my stuff alone but nope. It's a soft one so not for a power chewer. They might break it and swallow the bits.", user_id:molly.id)
item9 = Item.create(name:"mini tennis balls", description: "I won a dozen of them at an event. Unfortunately these don't have squeakers inside so Pawblo is not interested. Besides it's small so he might accidentally eat it.", user_id:paul.id)
item10 = Item.create(name:"halloween costume (bumblebee, small)", description: "Clover used this when she was a puppy. it's size medium so probably too big for Dray and Mugi, but might work for Stella, Flo, or Rose", user_id:fiona.id)
item11 = Item.create(name:"chunky sweater, large", description: "It says large but it's too small for Pawblo. I bought it at a post-christmas sale last year so it hasn't been used. it's off-white and got some snowflake patterns. It's Poly so you can toss it in a washer.", user_id:paul.id)
item12 = Item.create(name:"training clicker", description: "If anyone wants to try clicker training I got a clicker. I had some success with Clover but I don't think we'll continue.", user_id:fiona.id)
item13 = Item.create(name:"topical flea control", description: "I've switched to tablet type. These cover between 8 - 20lbs dogs. Still got 4 months supply in the box.", user_id:louise.id)
item14 = Item.create(name:"frisbee", description: "It's a competition-quality frisbee. It's got a few teeth marks on it but in good condition.", user_id:yui.id)
item15 = Item.create(name:"toothbrush", description: "This is a finger-sack type toothbrush. it's very soft so good for massaging gums, or for getting a puppy used to toothbrush too. ", user_id:aimee.id)
item16 = Item.create(name:"dog cookie cutter (bone-shaped)", description: "If you are inspired to bake some home-made dog biscuits, I got a bone-shaped cookie cutter. I got it as a gift but I'd never bake cookies for my dog.", user_id:louise.id)

tag1 = Tag.create(category:"walking")
tag2 = Tag.create(category:"food")
tag3 = Tag.create(category:"grooming")
tag4 = Tag.create(category:"puppy care")
tag5 = Tag.create(category:"play")

item_tags1 = ItemTag.create(item_id:item1.id, tag_id:tag4.id)
item_tags2 = ItemTag.create(item_id:item2.id, tag_id:tag3.id)
item_tags3 = ItemTag.create(item_id:item3.id, tag_id:tag4.id)
item_tags4 = ItemTag.create(item_id:item4.id, tag_id:tag1.id)
item_tags5 = ItemTag.create(item_id:item5.id, tag_id:tag4.id)
item_tags6 = ItemTag.create(item_id:item6.id, tag_id:tag1.id)
item_tags7 = ItemTag.create(item_id:item6.id, tag_id:tag1.id)
item_tags8 = ItemTag.create(item_id:item7.id, tag_id:tag2.id)
item_tags9 = ItemTag.create(item_id:item7.id, tag_id:tag4.id)
item_tags9 = ItemTag.create(item_id:item8.id, tag_id:tag5.id)
item_tags10 = ItemTag.create(item_id:item8.id, tag_id:tag4.id)
item_tags11 = ItemTag.create(item_id:item9.id, tag_id:tag4.id)
item_tags12 = ItemTag.create(item_id:item9.id, tag_id:tag5.id)
item_tags13 = ItemTag.create(item_id:item10.id, tag_id:tag1.id)
item_tags14 = ItemTag.create(item_id:item10.id, tag_id:tag5.id)
item_tags15 = ItemTag.create(item_id:item11.id, tag_id:tag1.id)
item_tags16 = ItemTag.create(item_id:item12.id, tag_id:tag1.id)
item_tags17 = ItemTag.create(item_id:item12.id, tag_id:tag4.id)
item_tags18 = ItemTag.create(item_id:item13.id, tag_id:tag3.id)
item_tags19 = ItemTag.create(item_id:item14.id, tag_id:tag5.id)
item_tags20 = ItemTag.create(item_id:item15.id, tag_id:tag3.id)
item_tags21 = ItemTag.create(item_id:item15.id, tag_id:tag4.id)
item_tags22 = ItemTag.create(item_id:item16.id, tag_id:tag2.id)
item_tags23 = ItemTag.create(item_id:item16.id, tag_id:tag4.id)
