# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

mio = User.create.(usename: "miok", password: "password", firstname: "Mio", lastname: "Kataoka")
aimee = User.create.(usename: "aimeek", password: "password", firstname: "Aimee", lastname: "Kalnoskas")
molly = User.create.(usename: "mollyb", password: "password", firstname: "Molly", lastname: "Bergstron")
yui = User.create.(usename: "yuii", password: "password", firstname: "Yui", lastname: "Ikeda")
fiona = User.create.(usename: "fionap", password: "password", firstname: "Fiona", lastname: "Peck")
paul = User.create.(usename: "pauly", password: "password", firstname: "Paul", lastname: "Yen")
louise = User.create.(usename: "louiser", password: "password", firstname: "Louise", lastname: "Rafkin")
phyllis = User.create.(usename: "phyllisr", password: "password", firstname: "Phyllis", lastname: "Ritchie")

dray = Dog.create(name:"Draymond", age: 4, breed: "Norwich", color: "red", user_id:mio.id)
axel = Dog.create(name:"Axel", age: 6, breed: "PWD", color: "black", owner: user_id:phyllis.id )
mugi = Dog.create(name:"Mugi", age: 2, breed: "Pomeranian", color: "fawn", user_id:yui.id )
rose = Dog.create(name:"Rose", age: 2, breed: "Schnoodle", color: "black and white", user_id:molly.id )
stella = Dog.create(name:"Stella", age: 3, breed: "mutt", color: "fawn", user_id:aimee.id )
clover = Dog.create(name:"Clover", age: 4, breed: "Jindo", color: "cream", user_id:fiona.id )
flo = Dog.create(name:"Florence", age: 5, breed: "mutt", color: "gret", user_id:louise.id )
pawblo = Dog.create(name:"Pawblo", age: 3, breed: "Husky", color: "grey", user_id:paul.id )

item1 = Item.create(name:"martingale collar", description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,", user_id:mio.id)
item2 = Item.create(name:"fine comb", description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text.", user_id:phyllis.id)
item3 = Item.create(name:"pee pad", description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text.", user_id:phyllis.id)
item4 = Item.create(name:"small harness", description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text.", user_id:mio.id)
item5 = Item.create(name:"bitter apple spray", description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text.", user_id:yui.id)
item6 = Item.create(name:"soft nylon puppy collar", description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text.", user_id:yui.id)
item7 = Item.create(name:"puppy food", description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text.", user_id:molly.id)
item8 = Item.create(name:"nylabone", description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text.", user_id:molly.id)
item9 = Item.create(name:"mini tennis balls", description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text.", user_id:paul.id)
item10 = Item.create(name:"halloween costume (bumblebee, small)", description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text.", user_id:fiona.id)
item11 = Item.create(name:"chunky sweater, small", description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text.", user_id:paul.id)
item12 = Item.create(name:"training clicker", description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text.", user_id:fiona.id)
item13 = Item.create(name:"topical flea control", description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text.", user_id:louise.id)
item14 = Item.create(name:"frisbee", description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text.", user_id:yui.id)
item15 = Item.create(name:"toothbrush", description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text.", user_id:aimee.id)
item16 = Item.create(name:"dog cookie cutter (bone-shaped)", description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text.", user_id:louise.id)

tag1 = Tag.create(category:"walking")
tag2 = Tag.create(category:"food")
tag3 = Tag.create(category:"grooming")
tag4 = Tag.create(category:"puppy care")

item_tags1 = ItemTag.create(item_id:item1.id, tag_id:tag4.id)
item_tags2 = ItemTag.create(item_id:item2.id, tag_id:tag3.id)
item_tags3 = ItemTag.create(item_id:item3.id, tag_id:tag4.id)
item_tags4 = ItemTag.create(item_id:item4.id, tag_id:tag1.id)
item_tags5 = ItemTag.create(item_id:item5.id, tag_id:tag4.id)
item_tags6 = ItemTag.create(item_id:item6.id, tag_id:tag1.id)
item_tags7 = ItemTag.create(item_id:item6.id, tag_id:tag1.id)
item_tags8 = ItemTag.create(item_id:item7.id, tag_id:tag2.id)
item_tags9 = ItemTag.create(item_id:item7.id, tag_id:tag4.id)
